[package]
name = "malloc_size_of_derive"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MIT/Apache-2.0"
publish = false

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
quote = "0.3.15"
syn = "0.11"
synstructure = "0.5"
