[package]
name = "lru_cache"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false # We should publish this at some point

[lib]
name = "lru_cache"
path = "lib.rs"

[dependencies]
arrayvec = "0.3.20"
