[package]
name = "fallible"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[lib]
name = "fallible"
path = "lib.rs"

[dependencies]
smallvec = "1.0"
hashbrown = "0.7"
