[package]
name = "style_derive"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
publish = false

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
darling = { version = "0.20", default-features = false }
derive_common = { path = "../derive_common" }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", default-features = false, features = ["clone-impls", "derive", "parsing"] }
synstructure = "0.13"
