name: CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]


jobs:
  linux-debug:
    name: Linux (Debug)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run Tests
        run: cargo build --features servo
        env:
          RUST_BACKTRACE: 1

  linux-release:
    name: Linux (Release)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run Tests
        run: cargo build --release --features servo
        env:
          RUST_BACKTRACE: 1

  build-result:
    name: Result
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - linux-debug
      - linux-release
    steps:
      - name: Success
        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

